version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=car_rental
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    volumes:
      - postgres_data:/var/lib/postgresql/db

  redis:
    image : redis:8.0.1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

volumes:
  postgres_data:
  redis_data:
