spring.application.name=car-rental

server.servlet.context-path=/api/v1
spring.profiles.active=development

spring.datasource.url=jdbc:postgresql://localhost:5432/car_rental
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver.class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false

jwt.secret=V1ZrSmp0eWRGdFJHc2VzRGdVRzU4cUlBc0RJSXlFSk8

cloudinary.cloud_name=atma-jaya-yogyakarta
cloudinary.api_key=283112394576554
cloudinary.api_secret=AXoDS9i7lFsXnM4ay6z0Vkaa8l8